### ISSUE TITLE
Incompatible with nn.parallel.DistributedDataParallel

### ISSUE THREAD

**Issue by llllearner** [archinetai/smart-pytorch#4]
Hi, thanks for you implementation.
But i found this code seem imcompatible with DDP training, and errors would happen in line
`# Get initial embeddings `
`embed = self.model.roberta.embeddings(input_ids)`
in your [https://github.com/archinetai/smart-pytorch#roberta-classification-example](url).

**Comment by flavioschneider** [comment]
Hi @YHL-Lab, I'm not familiar with DDP as I don't have multiple GPUs to work with. In any case that was just an example, you can change the eval function in any way (if it helps to work with DDP). You might also want to check out huggingface Accellerate https://huggingface.co/docs/accelerate/index

**Comment by llllearner** [comment]
Hi, @flavioschneider, I find that there is no problem with your code. Thanks for your reply.

**Comment by flavioschneider** [comment]
> Hi, @flavioschneider, I find that there is no problem with your code. Thanks for your reply.

Great!
